config/routes.rb
Rails.application.routes.draw do
  root to: 'feeds#index'
  get 'feeds/new_bulkload', to: 'feeds#new_bulkload'
  post 'feeds/bulkload', to: 'feeds#bulkload'
  resources :feeds do
    member do
      get 'refresh'
      post 'catchup'
      #post 'bulkload'
    end
    resources :items, only: [:show, :update]
  end
  namespace :api do
    namespace :xml do
      resources :feed, only: [:index]
    end
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  default_scope { order('title ASC') }
  validates :rss, presence: true, uniqueness: true
  validates :title, presence: true
  has_many :items

  include FeedsHelper

  @@feed_logger ||= Logger.new("#{Rails.root}/log/feed.log")

  def catch_up(number) # mark all but the x most recent items done
    current_items = self.items.where(donewith: false).order('pub_date DESC')
    if (current_items.count - number >= 0)
      remove_items = current_items.last(current_items.count - number)
      remove_items.each do |remove_item|
        Item.find(remove_item.id).update(donewith: true)
      end
    end
  end

  def self.from_rss_uri(rss_xml_uri)
    begin
      feed = Feedjira::Feed.fetch_and_parse(rss_xml_uri)
      new_feed_params = {
        rss: rss_xml_uri,
        description: feed.description,
        link: feed.url,
        title: feed.title
      }
      return Feed.new(new_feed_params)
    rescue Feedjira::NoParserAvailable
      @@feed_logger.info "Trying to parse #{rss_xml_uri} failed. It may be that invalid XML was returned - make sure this URL is a valid RSS feed"
    rescue Exception => e
      @@feed_logger.info "Uncaught error: #{e}"
      binding.pry
    end
    return nil
  end

  def fetch_new_items
    parsed_feed = Feedjira::Feed.fetch_and_parse(self.rss)

    errors = 0

    parsed_feed.entries.each do |entry|
      mp3_url = fetch_first_matching(entry, [:image, :enclosure_url])
      if mp3_url
        podcast_item_params = {
          mp3_url: mp3_url,
          title: entry.title,
          description: fetch_first_matching(entry, [:summary, :itunes_subtitle, :description, :itunes_summary]),
          pub_date: fetch_first_matching(entry, [:published, :pubDate])
        }
        item = self.items.new(podcast_item_params)

        if self.items.where("title = ?", podcast_item_params[:title]).length == 0
          @@feed_logger.info "Found new items '#{podcast_item_params[:title]}' for feed '#{self.title}'"
          if item.save == false
            @@feed_logger.error "Failed to save '#{podcast_item_params[:title]}' for feed '#{self.title}'"
            errors += 1
          end
        else
          @@feed_logger.info "Skipping Existing item '#{podcast_item_params[:title]}' for feed '#{self.title}'"
        end

      else
        @@feed_logger.info "Entry with no MP3 content"
      end

    end

    return errors
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  default_scope { order('pub_date DESC') }
  validates :mp3_url, presence: true
  validates :feed_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :feed,
                    message: "item title already taken for this feed" }
  belongs_to :feed

  def self.current
    Item.where(donewith: :false)
  end
  
end

app/controllers/api/xml/feed_controller.rb
class Api::Xml::FeedController < ApplicationController

  def index
    @items = Item.current
    respond_to do |format|
      format.xml  # index.builder
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :refresh, :catchup]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def bulkload
    #parse and load
    string_to_parse = params[:bulkdata]
    uris = string_to_parse.scan(/xmlUrl="https?:\S*"{1}/)
    uris.each do |uri|
      uri = uri.split('"')[1]
      if (uri =~ URI::regexp(%w(https http)))
        feed = Feed.from_rss_uri(uri)
        if feed
          feed.save
        end
      end
    end
    flash[:notice] = 'Feeds parsed and loaded.'
    render 'feeds/new_bulkload'
  end

  def catchup
    @feed.catch_up(4)
    redirect_to @feed
    flash[:notice] = 'Caught up to 4 most recent.'
  end

  def edit
  end

  def create

    begin
      if (feed_params["rss"] =~ URI::regexp(%w(https http))) == nil
        raise "Invalid URL"
      end
    rescue Exception => e
      @exception = e
      @feed = Feed.new
      return render :new
    end

    @feed = Feed.from_rss_uri(feed_params["rss"])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  def refresh
    @feed.fetch_new_items

    redirect_to @feed
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:rss, :description, :link, :title)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_feed, only: [:show, :update]
  before_action :set_item, only: [:show, :update]

  def show
  end

  def update
    respond_to do |format|
      if @item.update({ donewith: params[:donewith] })
        format.js {}
        #format.html redirect_to feed_path(@feed)
      end
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end
    def set_feed
      @feed = Feed.find(params[:feed_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def fetch_first_matching(object, array_of_params)
    array_of_params.each do |param|
      if object.try(param)
        return object[param]
      end
    end
    return nil
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed, :html => {:class => 'buffer'}) do |f| %>

  <div class="form-group">
    <%= f.label "URL to RSS Feed", { style: "display: none"} %><br>
    <%= f.text_field :rss, { class: "form-control input-lg", placeholder: "Feed URL" } %>
  </div>
  <div class="actions">
    <%= f.submit "Add RSS Feed", class: "btn btn-primary btn-block btn-lg" %>
  </div>
<% end %>

<%= render 'layouts/errors', :object => @feed %>
<%= render 'layouts/exception' %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<% @feeds.each do |feed| %>
  <%= button_to feed.title, feed_path(feed), method: "get", class: "btn btn-primary btn-lg btn-block" %>
<% end %>

<% content_for :footer do %>
  <%= link_to "Add Feed", new_feed_path, { class: "btn btn-warning btn-lg btn-block btn-nav" } %>
<% end %>

<% content_for :header do %>
  RSSer
<% end %>

app/views/feeds/new.html.erb
<% content_for :header do %>
New Feed
<% end %>

<%= render 'form' %>

<% content_for :footer, flush: true do %>
  <%= link_to "Back", :feeds, { class: "btn btn-warning btn-lg btn-block btn-nav" } %>
<% end %>

app/views/feeds/new_bulkload.html.erb
<%= form_tag(feeds_bulkload_path, method: "post") do %>
  <%= label_tag(:bulkdata, "Paste OPML:") %>
  <br>
  <%= text_area_tag(:bulkdata, "", :size => "20x10" ) %>
  <br>
  <%= submit_tag("Halt and Catch Fire", class: "btn btn-primary btn-lg btn-block") %>
<% end %>

app/views/feeds/show.html.erb
<% content_for :header do %>
  <%= @feed.title %>
<% end %>

<% content_for :menu do %>
  <li><%= link_to "Catch Up", catchup_feed_path(@feed), { method: "post" } %></li>
<% end %>

<%= link_to "Refresh Feed", refresh_feed_path(@feed), class: "btn btn-warning btn-lg btn-block" %>

<div id="render-items">
  <%= render @feed.items.current %>
</div>


<% content_for :footer do %>
  <%= link_to "Back", feeds_path, { class: "btn btn-warning btn-lg btn-block btn-nav" } %>
<% end %>

app/views/items/_item.html.erb
<div id="feed-<%= item.feed.id %>-item-<%= item.id %>" class="feed item">
  <%= button_to "X", feed_item_path(item.feed, item),
  { :remote => true,
    :controller => "items",
    :action => "update",
    :method => "patch",
    params: { donewith: true },
    class: "btn btn-danger btn-lg btn-done" } %>

  <%= link_to item.title, feed_item_path(item.feed, item), class: "btn btn-primary btn-lg btn-block" %>
</div>

app/views/items/show.html.erb
<% content_for :header do %>
  <%= @item.title %>
<% end %>

<div class="show-item-padding">
  <%= button_to "Hide/Mark Done", feed_item_path(@feed, @item),
  {:controller => "items",
    :action => "update",
    :method => "patch",
    params: { donewith: true },
    class: "btn btn-warning btn-lg btn-block btn-nav" } %>

  <div class="item-description">
    <%= raw @item.description %>
  </div>

  <%= link_to "Download", @item.mp3_url, { download: @item.mp3_url, class: "btn btn-info btn-lg btn-block" } %>

</div>

<% content_for :footer do %>
  <%= link_to "Back", :back, { class: "btn btn-warning btn-lg btn-block btn-nav" } %>
<% end %>

app/views/items/update.js.erb
console.log("items/update.js.erb")
$("#render-items").html("<%= j (render @feed.items.current) %>");

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this feed from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_exception.html.erb
<% if @exception %>
<div class="exception">
  <h4>an exception prohibited this feed from being saved:</h4>
  <p>
    <%= @exception.message %>
  </p>
</div>
<% end %>

<% content_for :footer, flush: true do %>
  <%= link_to "Back", :back, { class: "btn btn-warning btn-lg btn-block btn-nav" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsser</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div style=max-width="800px">

  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse col-md-6 col-md-offset-3">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand"><%= yield :header %></span>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/api/xml/feed.xml">Feed</a></li>
          <%= yield :menu %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

  <div id="top-buffer"></div>

  <div class="container-fluid">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
      <div id="bottom-buffer"></div>
    </div>

    <div class="col-md-6 col-md-offset-3 navbar-fixed-bottom">
      <div class="flash">
        <%= notice %>
        <%= alert %>
      </div>
      <footer class="footer">
        <%= yield :footer %>
      </footer>
    </div>
  </div>

  <div id="background"></div>

</div>



</body>
</html>